apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bsx9zbssc-python
  janus-idp.io/tekton: bsx9zbssc-python
  backstage.io/kubernetes-id: bsx9zbssc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bsx9zbssc-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
