apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bsx9zbssc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bsx9zbssc-python 
  name: bsx9zbssc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bsx9zbssc-python 
